package FrontOffice;

import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
import model.MySQL;


/**
 *
 * @author maleesha
 */
public class viewfoodorder extends javax.swing.JPanel {

    /**

     */
    public viewfoodorder() {
        initComponents();
        seting();
        load_fstatus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel2 = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jComboBox8 = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jComboBox9 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        jButton8.setBackground(new java.awt.Color(245, 71, 104));
        jButton8.setFont(new java.awt.Font("Microsoft JhengHei", 1, 13)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("update status");
        jButton8.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton8.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton8.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(619, Short.MAX_VALUE)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        add(jPanel2, java.awt.BorderLayout.PAGE_END);

        jPanel3.setLayout(new java.awt.GridBagLayout());

        jLabel10.setFont(new java.awt.Font("Microsoft JhengHei", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Status");

        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel13.setFont(new java.awt.Font("Microsoft JhengHei", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("coustomer ");

        jComboBox9.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox9ActionPerformed(evt);
            }
        });

        jButton1.setText("search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox9, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(190, 190, 190)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jComboBox8, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBox9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10)
                        .addComponent(jComboBox8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 17;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel3.add(jPanel1, gridBagConstraints);

        jTable4.setFont(new java.awt.Font("Microsoft YaHei", 0, 13)); // NOI18N
        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ticket id", "customer", "product", "id", "ordered time", "request time", "status", "quentity"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable4MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jTable4);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 793;
        gridBagConstraints.ipady = 301;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(25, 24, 50, 0);
        jPanel3.add(jScrollPane4, gridBagConstraints);

        add(jPanel3, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        String status = jComboBox8.getSelectedItem().toString();
        String nic = jComboBox8.getSelectedItem().toString();
        try {
            ResultSet stid = MySQL.execute("SELECT `id` FROM  `kot_status` WHERE `status`='" + status + "' ");
            ResultSet nicd = MySQL.execute("SELECT `id` FROM  `customer_visit_hotel` WHERE `customer_nic/passport`='" + nic + "' ");
            if (stid.next()) {
                if (nicd.next()) {
                    int st = stid.getInt("id");
                    int It = stid.getInt("id");
                    
                    MySQL.execute("UPDATE `kot` SET `kot_status_id`='" + st + "' WHERE `customer_visit_hotel_id`='" + It + "'");
                    
                }
            }
        } catch (Exception e) {
        }

    }//GEN-LAST:event_jButton8ActionPerformed
    
    private void load_fstatus() {
        try {
            jComboBox8.removeAllItems();
            Vector v = new Vector();
            
            ResultSet resultset = MySQL.execute("SELECT `status` FROM  `kot_status`");
            
            while (resultset.next()) {
                String fcato = resultset.getString("status");
                
                System.out.println(fcato);
                v.add(fcato);
                
                DefaultComboBoxModel def = new DefaultComboBoxModel(v);
                jComboBox8.setModel(def);
            }
        } catch (Exception e) {
            
        }
        
    }
    
    private void seting() {
        try {
            jComboBox9.removeAllItems();
            Vector v = new Vector();
            
            ResultSet resultset = MySQL.execute("SELECT `customer_nic/passport` FROM  `customer_visit_hotel`");
            
            while (resultset.next()) {
                String iato = resultset.getString("customer_nic/passport");
                
                System.out.println(iato);
                v.add(iato);
                
                DefaultComboBoxModel def = new DefaultComboBoxModel(v);
                jComboBox9.setModel(def);
            }
        } catch (Exception e) {
            
        }
        
    }
    
    private void oneclick() {
        int selectedRow = jTable4.getSelectedRow();
        if (selectedRow != -1) {
            String name = jTable4.getValueAt(selectedRow, 6).toString();
            
            jComboBox8.setSelectedItem(name);
            jComboBox9.setEnabled(false);
            
        }
        
    }
    
    private void reset() {
        DefaultTableModel tgbc = (DefaultTableModel) jTable4.getModel();
        tgbc.setRowCount(0);
        jComboBox9.setEnabled(true);
        jComboBox8.setSelectedItem(0);
        jComboBox9.setSelectedItem(0);
        
    }
    
    private void load() {
        
        String stu = jComboBox9.getSelectedItem().toString();
        try {
            DefaultTableModel tgbc = (DefaultTableModel) jTable4.getModel();
            tgbc.setRowCount(0);
            
            ResultSet rest = MySQL.execute("SELECT DISTINCT * FROM kot"
                    + " INNER JOIN kot_has_food ON kot.id=kot_has_food.kot_id "
                    + "INNER JOIN kot_status ON kot.kot_status_id = kot_status.id"
                    + " INNER JOIN customer_visit_hotel ON kot.customer_visit_hotel_id = customer_visit_hotel.id "
                    + "INNER JOIN food_item ON kot_has_food.food_item_id=food_item.id WHERE `customer_nic/passport`='" + stu + "' ");
            
            while (rest.next()) {
                
                int id = rest.getInt("id");
                String customer = rest.getString("customer_nic/passport");
                String name = rest.getString("name");
                
                String fooditem = rest.getString("food_item_id");
                
                String ordertime = rest.getString("ordered_time");
                String reqtime = rest.getString("req_time");
                String status = rest.getString("status");
                
                int qty = rest.getInt("qty");
                
                Vector vtc = new Vector();
                vtc.add(id);
                vtc.add(customer);
                vtc.add(name);
                
                vtc.add(fooditem);
                vtc.add(ordertime);
                vtc.add(reqtime);
                vtc.add(status);
                vtc.add(qty);
                
                tgbc.addRow(vtc);
                
            }
            
        } catch (Exception e) {
        }
        
    }
    private void jTable4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable4MouseClicked
        // TODO add your handling code here:

        if (evt.getClickCount() == 1) {
            oneclick();
        } else if (evt.getClickCount() == 2) {
            reset();
        }
    }//GEN-LAST:event_jTable4MouseClicked

    private void jComboBox9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox9ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jComboBox9ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        load();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton8;
    private javax.swing.JComboBox<String> jComboBox8;
    private javax.swing.JComboBox<String> jComboBox9;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable4;
    // End of variables declaration//GEN-END:variables
}
